name: tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        dependency-set: ["min", "latest"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          requirements_min.txt
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v3
    - name: Install minimum dependencies
      if: ${{ matrix.dependency-set == 'min' }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_min.txt
    - name: Install latest dependencies
      if: ${{ matrix.dependency-set == 'latest' }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Codecov
      if: ${{ matrix.python-version == '3.13' && matrix.dependency-set == 'latest' }}
      run: |
        pip install codecov
    - name: Run tests without coverage
      if: ${{ !(matrix.python-version == '3.13' && matrix.dependency-set == 'latest') }}
      run: |
        python -m unittest discover -s tests
    - name: Run tests with coverage and generate coverage report
      if: ${{ matrix.python-version == '3.13' && matrix.dependency-set == 'latest' }}
      env:
        NUMBA_JIT_COVERAGE: "1"
      run: |
        coverage run --source=pterasoftware -m unittest discover -s tests
        coverage xml -o coverage.xml
    - name: Upload coverage report to Codecov
      if: ${{ matrix.python-version == '3.13' && matrix.dependency-set == 'latest' }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: true
